In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="whitegrid",color_codes=True)
import pandas as pd
import keras

Using TensorFlow backend.


In [6]:
from keras.layers import Dense
from keras.models import Sequential
from keras.callbacks import EarlyStopping
from keras.utils import to_categorical

In [10]:
df=pd.read_csv("C:\\Users\\Admin\Desktop\\digits classifier\\using keras\\train.csv")

In [22]:
x_test=pd.read_csv("C:\\Users\\Admin\Desktop\\digits classifier\\using keras\\test.csv")

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB


In [16]:
df.head(3)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  

[3 rows x 785 columns]

In [33]:
y_trainx=df.label
x_train=df.drop("label",axis=1)

In [43]:
y_train=to_categorical(y_trainx)

In [44]:
#print(y_train)

[[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [61]:
model=Sequential()
model.add(Dense(init="uniform",input_dim=784,output_dim=60,activation="relu"))

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=784, activation="relu", units=60, kernel_initializer="uniform")`
  


In [62]:
model.add(Dense(init="uniform",output_dim=60,activation="relu"))

model.add(Dense(init="uniform",output_dim=50,activation="relu"))

model.add(Dense(init="uniform",output_dim=30,activation="relu"))

model.add(Dense(init="uniform",output_dim=10,activation="softmax"))

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=60, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=50, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=30, kernel_initializer="uniform")`
  """
C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=10, kernel_initializer="uniform")`
  import sys


In [72]:
monitoring=EarlyStopping(patience=5)
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])
monitoring=EarlyStopping(patience=5)

In [67]:
model.fit(x_train,y_train,epochs=20,callbacks=[monitoring],validation_split=0.2)

Train on 33600 samples, validate on 8400 samples
Epoch 1/20
33600/33600 [==============================] - 8s 250us/step - loss: 0.0308 - acc: 0.9922 - val_loss: 0.0730 - val_acc: 0.9857
Epoch 2/20
33600/33600 [==============================] - 9s 254us/step - loss: 0.0213 - acc: 0.9942 - val_loss: 0.0577 - val_acc: 0.9863
Epoch 3/20
33600/33600 [==============================] - 9s 280us/step - loss: 0.0205 - acc: 0.9943 - val_loss: 0.0548 - val_acc: 0.9867
Epoch 4/20
33600/33600 [==============================] - 9s 258us/step - loss: 0.0255 - acc: 0.9936 - val_loss: 0.0550 - val_acc: 0.9893
Epoch 5/20
33600/33600 [==============================] - 9s 254us/step - loss: 0.0222 - acc: 0.9945 - val_loss: 0.0662 - val_acc: 0.9868
Epoch 6/20
33600/33600 [==============================] - 9s 258us/step - loss: 0.0296 - acc: 0.9933 - val_loss: 0.0581 - val_acc: 0.9854
Epoch 7/20
33600/33600 [==============================] - 9s 261us/step - loss: 0.0287 - acc: 0.9937 - val_loss: 0.0507 - v

In [76]:
predictions=model.predict_classes(x_test)

In [82]:
pd.DataFrame({"ImageId": range(1,len(predictions)+1,1), "Label": predictions}).to_csv("mak.csv",index=False)